In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import keras
from keras.layers import Dense
from keras.models import Sequential

import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set()

mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)


In [2]:
print("categorical labels")
print(y_train[0:5])

# make labels one hot encoded
y_train = tf.one_hot(y_train, 10)
y_test = tf.one_hot(y_test, 10)

print("one hot encoded labels")
print(y_train[0:5])

categorical labels
[5 0 4 1 9]
one hot encoded labels
tf.Tensor(
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]], shape=(5, 10), dtype=float32)


In [3]:
train_ds = tf.data.Dataset.from_tensor_slices((x_train, y_train)).batch(50)
test_ds = tf.data.Dataset.from_tensor_slices((x_test, y_test)).batch(50)
train_ds

<BatchDataset element_spec=(TensorSpec(shape=(None, 28, 28), dtype=tf.uint8, name=None), TensorSpec(shape=(None, 10), dtype=tf.float32, name=None))>

In [5]:
# showing an example of the Flatten class and operation
from tensorflow.keras.layers import Flatten
flatten = Flatten(dtype='float32')

"original data shape"
print(x_train.shape)

"flattened shape"
print(flatten(x_train).shape)

(60000, 28, 28)
(60000, 784)


In [8]:
X_train = flatten(x_train)
X_test = flatten(x_test)

In [9]:
# Instantiate a sequential model
model1 = Sequential()
  
# Add dense layers
model1.add(Dense(128, input_shape=(784,), activation='relu'))
model1.add(Dense(256, activation='relu'))
model1.add(Dense(128, activation='relu'))
model1.add(Dense(64, activation='relu'))
  
# Add a dense layer with as many neurons as prosper rating
model1.add(Dense(10, activation='softmax'))
  
# Compile your model using categorical_crossentropy loss
model1.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [10]:
# Fit your model to the training data for 200 epochs
model1.fit(X_train, y_train, validation_split=0.25, epochs=50)

# Evaluate your model accuracy on the test data
accuracy = model1.evaluate(X_test, y_test)[1]

# Print accuracy
print('Accuracy:', accuracy)

# Predict on coords_small_test
preds = model1.predict(X_test)

# Print preds vs true values
print("{:45} | {}".format('Raw Model Predictions','True labels'))
for i,pred in enumerate(preds):
    print("{} | {}".format(pred,y_test[i]))

# Extract the position of highest probability from each pred vector
preds_chosen = [np.argmax(pred) for pred in preds]

# Print preds vs true values
print("{:10} | {}".format('Rounded Model Predictions','True labels'))
for i,pred in enumerate(preds_chosen):
    print("{:25} | {}".format(pred,y_test[i]))

Epoch 1/50
1407/1407 [==============================] - 9s 4ms/step - loss: 0.6247 - accuracy: 0.8747 - val_loss: 0.2354 - val_accuracy: 0.9344
Epoch 2/50
1407/1407 [==============================] - 6s 4ms/step - loss: 0.1990 - accuracy: 0.9440 - val_loss: 0.2247 - val_accuracy: 0.9386
Epoch 3/50
1407/1407 [==============================] - 14s 10ms/step - loss: 0.1507 - accuracy: 0.9564 - val_loss: 0.1679 - val_accuracy: 0.9544
Epoch 4/50
1407/1407 [==============================] - 13s 10ms/step - loss: 0.1312 - accuracy: 0.9631 - val_loss: 0.1552 - val_accuracy: 0.9581
Epoch 5/50
1407/1407 [==============================] - 14s 10ms/step - loss: 0.1148 - accuracy: 0.9668 - val_loss: 0.1479 - val_accuracy: 0.9619
Epoch 6/50
1407/1407 [==============================] - 14s 10ms/step - loss: 0.0987 - accuracy: 0.9719 - val_loss: 0.1465 - val_accuracy: 0.9632
Epoch 7/50
1407/1407 [==============================] - 14s 10ms/step - loss: 0.0870 - accuracy: 0.9752 - val_loss: 0.1512 - val

In [11]:
accuracy # on unseen data

0.9750999808311462

#### we used 50 epochs however, you can just use 10 and you will also get a great accuracy.